language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler -v 2.1.4
- gem install node -v 8.12.0
- bundle
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: ENV['heroku_app_id']
  app: joe-joey-viewing-party
  run: rails db:migrate
  
